/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    // Site-wide type scale: 8, 12, 15, 20, 24, 28 only.
    // Remap Tailwind defaults so text-sm/base/lg/… never emit off-scale sizes.
    fontSize: {
      xs: ['12px', { lineHeight: '1.4' }],
      sm: ['15px', { lineHeight: '1.45' }],
      base: ['15px', { lineHeight: '1.5' }],
      lg: ['20px', { lineHeight: '1.35' }],
      xl: ['20px', { lineHeight: '1.3' }],
      '2xl': ['24px', { lineHeight: '1.25' }],
      '3xl': ['28px', { lineHeight: '1.2' }],
      '4xl': ['28px', { lineHeight: '1.15' }],
      '5xl': ['28px', { lineHeight: '1.1' }],
      '6xl': ['28px', { lineHeight: '1.1' }],
      '7xl': ['28px', { lineHeight: '1.05' }],
      '8xl': ['28px', { lineHeight: '1' }],
      '9xl': ['28px', { lineHeight: '1' }],
    },
    extend: {
      fontFamily: {
        sans: [
          'Inter Variable',
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
        display: [
          'Inter Variable',
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
        serif: [
          'Inter Variable',
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
      },
      colors: {
        pe: {
          canvas: 'var(--pe-canvas)',
          surface: 'var(--pe-surface)',
          elevated: 'var(--pe-elevated)',
          sidebar: 'var(--pe-sidebar)',
          text: 'var(--pe-text)',
          'text-secondary': 'var(--pe-text-secondary)',
          'text-muted': 'var(--pe-text-muted)',
          border: 'var(--pe-border)',
          'border-strong': 'var(--pe-border-strong)',
          accent: 'var(--pe-accent)',
          'accent-pressed': 'var(--pe-accent-pressed)',
          'accent-wash': 'var(--pe-accent-wash)',
          'accent-border': 'var(--pe-accent-border)',
          link: 'var(--pe-link)',
          positive: 'var(--pe-positive)',
          negative: 'var(--pe-negative)',
          warning: 'var(--pe-warning)',
          ticker: 'var(--pe-ticker)',
          ink: 'var(--pe-ink)',
        },
      },
      maxWidth: {
        // Substack centers the feed column; ~640px reads well beside a 232px nav.
        feed: '40rem',
      },
    },
  },
  plugins: [],
};
