/**
 * USD IBKR listings for catalog/demo baskets (synced from ibkr_instruments).
 * Prefer US stocks/ADRs; SMCI resolves to Super Micro Computer, not leveraged ETF.
 */

/** @type {Record<string, object>} */
export const CATALOG_INSTRUMENTS = {
  AAPL: {
    conid: 265598,
    symbol: 'AAPL',
    name: 'APPLE INC',
    exchange: 'NASDAQ',
    currency: 'USD',
    country: 'US',
    isin: 'US0378331005',
    localSymbol: 'AAPL',
    instrumentType: 'STK',
  },
  AMD: {
    conid: 4391,
    symbol: 'AMD',
    name: 'ADVANCED MICRO DEVICES',
    exchange: 'MEMX',
    currency: 'USD',
    country: 'US',
    isin: 'US0079031078',
    localSymbol: 'AMD',
    instrumentType: 'STK',
  },
  AMZN: {
    conid: 3691937,
    symbol: 'AMZN',
    name: 'AMAZON.COM INC',
    exchange: 'CHX',
    currency: 'USD',
    country: 'US',
    isin: 'US0231351067',
    localSymbol: 'AMZN',
    instrumentType: 'STK',
  },
  ANET: {
    conid: 740948854,
    symbol: 'ANET',
    name: 'ARISTA NETWORKS INC',
    exchange: 'MEMX',
    currency: 'USD',
    country: 'US',
    isin: 'US0404132054',
    localSymbol: 'ANET',
    instrumentType: 'STK',
  },
  AVGO: {
    conid: 313130367,
    symbol: 'AVGO',
    name: 'BROADCOM INC',
    exchange: 'DRCTEDGE',
    currency: 'USD',
    country: 'US',
    isin: 'US11135F1012',
    localSymbol: 'AVGO',
    instrumentType: 'STK',
  },
  DLR: {
    conid: 31832526,
    symbol: 'DLR',
    name: 'DIGITAL REALTY TRUST INC.',
    exchange: 'AMEX',
    currency: 'USD',
    country: 'US',
    isin: 'US2538681030',
    localSymbol: 'DLR',
    instrumentType: 'STK',
  },
  EQIX: {
    conid: 181764593,
    symbol: 'EQIX',
    name: 'EQUINIX INC',
    exchange: 'BEX',
    currency: 'USD',
    country: 'US',
    isin: 'US29444U7000',
    localSymbol: 'EQIX',
    instrumentType: 'STK',
  },
  GOOGL: {
    conid: 208813719,
    symbol: 'GOOGL',
    name: 'ALPHABET INC-CL A',
    exchange: 'NYSE',
    currency: 'USD',
    country: 'US',
    isin: 'US02079K3059',
    localSymbol: 'GOOGL',
    instrumentType: 'STK',
  },
  IBM: {
    conid: 8314,
    symbol: 'IBM',
    name: 'INTL BUSINESS MACHINES CORP',
    exchange: 'CHX',
    currency: 'USD',
    country: 'US',
    isin: 'US4592001014',
    localSymbol: 'IBM',
    instrumentType: 'STK',
  },
  JNJ: {
    conid: 8719,
    symbol: 'JNJ',
    name: 'JOHNSON & JOHNSON',
    exchange: 'MEMX',
    currency: 'USD',
    country: 'US',
    isin: 'US4781601046',
    localSymbol: 'JNJ',
    instrumentType: 'STK',
  },
  KO: {
    conid: 8894,
    symbol: 'KO',
    name: 'COCA-COLA CO/THE',
    exchange: 'ARCA',
    currency: 'USD',
    country: 'US',
    isin: 'US1912161007',
    localSymbol: 'KO',
    instrumentType: 'STK',
  },
  LCID: {
    conid: 810758322,
    symbol: 'LCID',
    name: 'LUCID GROUP INC',
    exchange: 'NYSE',
    currency: 'USD',
    country: 'US',
    isin: 'US5494982029',
    localSymbol: 'LCID',
    instrumentType: 'STK',
  },
  LI: {
    conid: 436980133,
    symbol: 'LI',
    name: 'LI AUTO INC - ADR',
    exchange: 'BYX',
    currency: 'USD',
    country: 'US',
    isin: 'US50202M1027',
    localSymbol: 'LI',
    instrumentType: 'STK',
  },
  MMM: {
    conid: 9720,
    symbol: 'MMM',
    name: '3M CO',
    exchange: 'PEARL',
    currency: 'USD',
    country: 'US',
    isin: 'US88579Y1010',
    localSymbol: 'MMM',
    instrumentType: 'STK',
  },
  MSFT: {
    conid: 272093,
    symbol: 'MSFT',
    name: 'MICROSOFT CORP',
    exchange: 'NASDAQ',
    currency: 'USD',
    country: 'US',
    isin: 'US5949181045',
    localSymbol: 'MSFT',
    instrumentType: 'STK',
  },
  NIO: {
    conid: 562595576,
    symbol: 'NIO',
    name: 'NIO INC-CLASS A',
    exchange: 'SGX',
    currency: 'USD',
    country: 'SG',
    isin: 'KYG6525F1028',
    localSymbol: 'NIO',
    instrumentType: 'STK',
  },
  NVDA: {
    conid: 4815747,
    symbol: 'NVDA',
    name: 'NVIDIA CORP',
    exchange: 'IEX',
    currency: 'USD',
    country: 'US',
    isin: 'US67066G1040',
    localSymbol: 'NVDA',
    instrumentType: 'STK',
  },
  PEP: {
    conid: 11017,
    symbol: 'PEP',
    name: 'PEPSICO INC',
    exchange: 'BEX',
    currency: 'USD',
    country: 'US',
    isin: 'US7134481081',
    localSymbol: 'PEP',
    instrumentType: 'STK',
  },
  PG: {
    conid: 11054,
    symbol: 'PG',
    name: 'PROCTER & GAMBLE CO/THE',
    exchange: 'T24X',
    currency: 'USD',
    country: 'US',
    isin: 'US7427181091',
    localSymbol: 'PG',
    instrumentType: 'STK',
  },
  RIVN: {
    conid: 525768800,
    symbol: 'RIVN',
    name: 'RIVIAN AUTOMOTIVE INC-A',
    exchange: 'AMEX',
    currency: 'USD',
    country: 'US',
    isin: 'US76954A1034',
    localSymbol: 'RIVN',
    instrumentType: 'STK',
  },
  SMCI: {
    conid: 731466419,
    symbol: 'SMCI',
    name: 'SUPER MICRO COMPUTER INC',
    exchange: 'BATS',
    currency: 'USD',
    country: 'US',
    isin: 'US86800U3023',
    localSymbol: 'SMCI',
    instrumentType: 'STK',
  },
  T: {
    conid: 37018770,
    symbol: 'T',
    name: 'AT&T INC',
    exchange: 'EDGX',
    currency: 'USD',
    country: 'US',
    isin: 'US00206R1023',
    localSymbol: 'T',
    instrumentType: 'STK',
  },
  TSLA: {
    conid: 76792991,
    symbol: 'TSLA',
    name: 'TESLA INC',
    exchange: 'NASDAQ',
    currency: 'USD',
    country: 'US',
    isin: 'US88160R1014',
    localSymbol: 'TSLA',
    instrumentType: 'STK',
  },
  TSM: {
    conid: 6223250,
    symbol: 'TSM',
    name: 'TAIWAN SEMICONDUCTOR-SP ADR',
    exchange: 'PEARL',
    currency: 'USD',
    country: 'US',
    isin: 'US8740391003',
    localSymbol: 'TSM',
    instrumentType: 'STK',
  },
  VRT: {
    conid: 402783527,
    symbol: 'VRT',
    name: 'VERTIV HOLDINGS CO-A',
    exchange: 'NYSENAT',
    currency: 'USD',
    country: 'US',
    isin: 'US92537N1081',
    localSymbol: 'VRT',
    instrumentType: 'STK',
  },
  VZ: {
    conid: 4901,
    symbol: 'VZ',
    name: 'VERIZON COMMUNICATIONS INC',
    exchange: 'NYSENAT',
    currency: 'USD',
    country: 'US',
    isin: 'US92343V1044',
    localSymbol: 'VZ',
    instrumentType: 'STK',
  },
};

export function catalogConstituent(symbol, { weight, segment }) {
  const inst = CATALOG_INSTRUMENTS[symbol];
  if (!inst) {
    throw new Error(`Missing catalog instrument mapping for ${symbol}`);
  }
  return {
    ...inst,
    weight,
    segment,
    isCustom: false,
  };
}

export function catalogConstituents(rows) {
  return rows.map((row) => catalogConstituent(row.symbol, row));
}
