import { catalogConstituents } from './catalogInstruments.js';
import { CATALOG_BASKET_IDS } from './catalogIds.js';

/** Seed payloads for catalog baskets → live DB rows with NAV tracking. */
export const CATALOG_SEED_BASKETS = [
  {
    id: CATALOG_BASKET_IDS['ai-data-center'],
    catalogSlug: 'ai-data-center',
    name: 'AI & Data Center Theme',
    shortDescription: 'Physical infrastructure behind AI, cloud, and digital revolutions.',
    description:
      'India is witnessing a structural surge in data localisation, AI workloads, and cloud adoption. This basket captures the infrastructure layer that benefits irrespective of which tech platform wins.',
    imageUrl:
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=960&h=600&fit=crop&q=80',
    imageGradient: 'from-violet-600 to-cyan-500',
    weightingType: 'custom',
    rebalanceFrequency: 'quarterly',
    constituents: catalogConstituents([
      { symbol: 'NVDA', weight: 12, segment: 'Largecap' },
      { symbol: 'MSFT', weight: 10, segment: 'Largecap' },
      { symbol: 'AMZN', weight: 9, segment: 'Largecap' },
      { symbol: 'GOOGL', weight: 9, segment: 'Largecap' },
      { symbol: 'EQIX', weight: 8, segment: 'Largecap' },
      { symbol: 'DLR', weight: 7, segment: 'Midcap' },
      { symbol: 'ANET', weight: 7, segment: 'Midcap' },
      { symbol: 'SMCI', weight: 8, segment: 'Smallcap' },
      { symbol: 'VRT', weight: 8, segment: 'Midcap' },
      { symbol: 'TSM', weight: 10, segment: 'Largecap' },
      { symbol: 'AVGO', weight: 6, segment: 'Largecap' },
      { symbol: 'AMD', weight: 6, segment: 'Largecap' },
    ]),
    metadata: {
      badge: 'hot',
      type: 'Thematic',
      tags: ['AI', 'Infrastructure', 'Cloud'],
      stats: {
        returnLabel: 'Live NAV',
        minInvestAmount: 5000,
        volatility: 'High Volatility',
      },
      creatorName: 'Growth Investing',
      followers: 1240,
      methodology: [
        { title: 'Defining the universe', body: 'Companies engaged in AI, cloud, data center, and digital infrastructure.' },
        { title: 'Constituent screening', body: 'Sector relevance, financial health, strategic moat, valuation discipline, and governance.' },
        { title: 'Weighting', body: 'Quant-driven allocation using momentum, relative strength, liquidity, and risk signals.' },
        { title: 'Rebalance', body: 'Quarterly rebalance to realign weights with the strategy.' },
      ],
      factsheet: {
        launched: 'Jan 2026',
        rebalance: 'Quarterly',
        benchmark: 'Nifty 500',
        expenseNote: 'No direct expense ratio; platform fees apply on invest.',
      },
      risk: {
        volatilityLabel: 'High',
        sharpeRatio: 1.12,
        maxDrawdown: -14.2,
        pe: 68.8,
        pb: 9.16,
        divYield: 0.32,
      },
    },
  },
  {
    id: CATALOG_BASKET_IDS['us-tech-giants'],
    catalogSlug: 'us-tech-giants',
    name: 'US Tech Giants',
    shortDescription: 'Leading American technology companies driving global innovation.',
    description: 'Invest in the megacap technology leaders with durable cash flows and platform moats.',
    imageUrl:
      'https://images.unsplash.com/photo-1518770660439-4636190af475?w=960&h=600&fit=crop&q=80',
    imageGradient: 'from-emerald-600 to-teal-500',
    weightingType: 'equal',
    rebalanceFrequency: 'quarterly',
    constituents: catalogConstituents([
      { symbol: 'AAPL', weight: 20, segment: 'Largecap' },
      { symbol: 'MSFT', weight: 20, segment: 'Largecap' },
      { symbol: 'GOOGL', weight: 20, segment: 'Largecap' },
      { symbol: 'AMZN', weight: 20, segment: 'Largecap' },
      { symbol: 'NVDA', weight: 20, segment: 'Largecap' },
    ]),
    metadata: {
      badge: 'trending',
      type: 'Thematic',
      tags: ['US', 'Technology'],
      stats: { returnLabel: 'Live NAV', minInvestAmount: 5000, volatility: 'Medium Volatility' },
      creatorName: 'PocketEdge Research',
      followers: 3890,
    },
  },
  {
    id: CATALOG_BASKET_IDS['global-ev'],
    catalogSlug: 'global-ev',
    name: 'Global EV Revolution',
    shortDescription: 'Electric vehicle manufacturers and suppliers worldwide.',
    description: 'Exposure to the electrification of transport across OEMs and battery supply chain.',
    imageUrl:
      'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=960&h=600&fit=crop&q=80',
    imageGradient: 'from-lime-600 to-emerald-500',
    weightingType: 'equal',
    rebalanceFrequency: 'quarterly',
    constituents: catalogConstituents([
      { symbol: 'TSLA', weight: 20, segment: 'Largecap' },
      { symbol: 'RIVN', weight: 20, segment: 'Smallcap' },
      { symbol: 'NIO', weight: 20, segment: 'Midcap' },
      { symbol: 'LI', weight: 20, segment: 'Midcap' },
      { symbol: 'LCID', weight: 20, segment: 'Smallcap' },
    ]),
    metadata: {
      badge: 'trending',
      type: 'Thematic',
      tags: ['EV', 'Clean Energy'],
      stats: { returnLabel: 'Live NAV', minInvestAmount: 5000, volatility: 'High Volatility' },
      creatorName: 'PocketEdge Research',
      followers: 2105,
    },
  },
  {
    id: CATALOG_BASKET_IDS['dividend-quality'],
    catalogSlug: 'dividend-quality',
    name: 'Dividend Quality Leaders',
    shortDescription: 'Stable dividend payers with strong balance sheets.',
    description: 'Quality compounders with consistent payout histories and defensive characteristics.',
    imageUrl:
      'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=960&h=600&fit=crop&q=80',
    imageGradient: 'from-amber-600 to-orange-500',
    weightingType: 'custom',
    rebalanceFrequency: 'quarterly',
    constituents: catalogConstituents([
      { symbol: 'JNJ', weight: 15, segment: 'Largecap' },
      { symbol: 'PG', weight: 15, segment: 'Largecap' },
      { symbol: 'KO', weight: 14, segment: 'Largecap' },
      { symbol: 'PEP', weight: 14, segment: 'Largecap' },
      { symbol: 'VZ', weight: 14, segment: 'Largecap' },
      { symbol: 'T', weight: 13, segment: 'Largecap' },
      { symbol: 'MMM', weight: 13, segment: 'Largecap' },
      { symbol: 'IBM', weight: 12, segment: 'Largecap' },
    ]),
    metadata: {
      badge: 'hidden_gem',
      type: 'Strategy',
      tags: ['Dividend', 'Quality'],
      stats: { returnLabel: 'Live NAV', minInvestAmount: 3000, volatility: 'Low Volatility' },
      creatorName: 'Income Desk',
      followers: 876,
    },
  },
];
