/**
 * User scenarios for social.pocketedge — drives the design guide screen gallery.
 * Source of truth for copy: social/USER_SCENARIOS.md
 */
export const SCENARIO_PHASES = [
  { id: 'acquisition', label: 'Acquisition & auth' },
  { id: 'onboarding', label: 'Post-login onboarding' },
  { id: 'feed', label: 'Feed & posts' },
  { id: 'discovery', label: 'Search & discovery' },
  { id: 'markets', label: 'Markets & portfolio' },
  { id: 'profile', label: 'Profile & portfolios' },
  { id: 'activity', label: 'Activity & notifications' },
  { id: 'settings', label: 'Settings & account' },
];

export const SOCIAL_USER_SCENARIOS = [
  // Acquisition & auth
  {
    id: 'landing',
    phase: 'acquisition',
    name: 'Marketing home (logged out)',
    screen: 'LandingHomeScreen',
    status: 'built',
    preconditions: 'Visitor opens social.pocketedge.in without a session.',
    userAction: 'Scroll value props; tap Get started or Sign in.',
    expectedResult:
      'See hero, sample feed preview, disclosure promise, and CTAs. Sign in opens auth; Get started starts signup.',
  },
  {
    id: 'login',
    phase: 'acquisition',
    name: 'Login',
    screen: 'LoginScreen',
    status: 'built',
    preconditions: 'User tapped Sign in from landing or hit a protected route.',
    userAction: 'Continue with Google or enter email for magic link.',
    expectedResult:
      'OAuth or magic-link flow completes; existing users land on For You feed; new users enter onboarding.',
  },
  {
    id: 'signup',
    phase: 'acquisition',
    name: 'Sign up',
    screen: 'SignupScreen',
    status: 'built',
    preconditions: 'New user chose Get started.',
    userAction: 'Accept terms; continue with Google or email.',
    expectedResult: 'Account created; redirect to onboarding step 1 (welcome).',
  },

  // Onboarding
  {
    id: 'onboard-welcome',
    phase: 'onboarding',
    name: 'Welcome',
    screen: 'OnboardWelcomeScreen',
    status: 'built',
    preconditions: 'First login; onboarding not completed.',
    userAction: 'Tap Continue.',
    expectedResult: 'Explain skin-in-the-game disclosure; advance to profile setup.',
  },
  {
    id: 'onboard-profile',
    phase: 'onboarding',
    name: 'Profile setup',
    screen: 'OnboardProfileScreen',
    status: 'built',
    preconditions: 'Onboarding step 2.',
    userAction: 'Set display name, @handle, optional bio and avatar.',
    expectedResult: 'Handle uniqueness validated; Continue enabled when name + handle valid.',
  },
  {
    id: 'onboard-follow',
    phase: 'onboarding',
    name: 'Follow investors',
    screen: 'OnboardFollowScreen',
    status: 'built',
    preconditions: 'Onboarding step 3.',
    userAction: 'Follow at least 3 suggested investors.',
    expectedResult: 'Following count updates; Continue unlocks at ≥3 follows.',
  },
  {
    id: 'onboard-topics',
    phase: 'onboarding',
    name: 'Follow topics',
    screen: 'OnboardTopicsScreen',
    status: 'built',
    preconditions: 'Onboarding step 4.',
    userAction: 'Select topics (India equities, US tech, etc.).',
    expectedResult: 'Topics saved; Following feed and For You ranking seeded.',
  },
  {
    id: 'onboard-portfolio',
    phase: 'onboarding',
    name: 'Add first portfolio (optional)',
    screen: 'OnboardPortfolioScreen',
    status: 'built',
    preconditions: 'Onboarding step 5.',
    userAction: 'Create a portfolio with name + thesis, add holdings, or Skip for now.',
    expectedResult: 'Portfolio saved for disclosure; skip lands on feed with empty portfolio prompt.',
  },
  {
    id: 'onboard-disclosure',
    phase: 'onboarding',
    name: 'Disclosure agreement',
    screen: 'OnboardDisclosureScreen',
    status: 'built',
    preconditions: 'Final onboarding step.',
    userAction: 'Read disclosure rules; check agree; tap Enter feed.',
    expectedResult: 'onboarding_completed flag set; land on For You feed with compose FAB.',
  },

  // Feed & posts
  {
    id: 'feed-for-you',
    phase: 'feed',
    name: 'For You feed',
    screen: 'FeedForYouScreen',
    status: 'built',
    preconditions: 'Logged in; default tab Feed.',
    userAction: 'Scroll posts; tap author, ticker, or post body.',
    expectedResult: 'Ranked posts with XIRR, disclosure chips; navigation to profile, ticker card, or post detail.',
  },
  {
    id: 'feed-following-empty',
    phase: 'feed',
    name: 'Following feed (empty)',
    screen: 'FeedFollowingEmptyScreen',
    status: 'built',
    preconditions: 'User follows nobody and no topics.',
    userAction: 'Switch feed to Following via header dropdown.',
    expectedResult: 'Empty state with prompt to follow people or topics; link to Search.',
  },
  {
    id: 'compose-post',
    phase: 'feed',
    name: 'Compose text post',
    screen: 'ComposePostScreen',
    status: 'built',
    preconditions: 'On Feed tab.',
    userAction: 'Tap FAB; write thesis with $TICKER; tap Post.',
    expectedResult: 'Post prepended to feed; tickers trigger position disclosure strip on publish.',
  },
  {
    id: 'compose-image',
    phase: 'feed',
    name: 'Compose with image',
    screen: 'ComposeImageScreen',
    status: 'built',
    preconditions: 'Compose modal open.',
    userAction: 'Tap Image; select file; add caption; Post.',
    expectedResult: 'Image uploaded; post shows image card in feed; disclosure still applies to tickers.',
  },
  {
    id: 'post-detail',
    phase: 'feed',
    name: 'Post detail',
    screen: 'PostDetailScreen',
    status: 'built',
    preconditions: 'User opened a post from feed or activity.',
    userAction: 'Read full post; like; view comments.',
    expectedResult: 'Full body, disclosure, comments list; mobile back in shell only.',
  },
  {
    id: 'add-comment',
    phase: 'feed',
    name: 'Add comment',
    screen: 'AddCommentScreen',
    status: 'built',
    preconditions: 'Post detail open.',
    userAction: 'Type comment; tap Reply.',
    expectedResult: 'Comment appended; author disclosure chip shown if comment mentions tickers.',
  },
  {
    id: 'ticker-disclosure',
    phase: 'feed',
    name: 'Ticker mini-card',
    screen: 'TickerDisclosureScreen',
    status: 'built',
    preconditions: 'Post contains $TICKER user holds or author holds.',
    userAction: 'Tap underlined ticker.',
    expectedResult: 'Desktop: inline popover with position. Mobile: bottom sheet with qty, avg cost, P&L.',
  },

  // Search & discovery
  {
    id: 'search-landing',
    phase: 'discovery',
    name: 'Search (no query)',
    screen: 'SearchLandingScreen',
    status: 'built',
    preconditions: 'Search tab selected.',
    userAction: 'Browse trending topics, suggested people, trending stocks.',
    expectedResult: 'Follow toggles on topics/people; tap person → profile; tap stock → markets detail.',
  },
  {
    id: 'search-people',
    phase: 'discovery',
    name: 'Search people results',
    screen: 'SearchPeopleScreen',
    status: 'built',
    preconditions: 'Query matches people.',
    userAction: 'Type name or handle; tap result or Follow.',
    expectedResult: 'Filtered list; Follow persists; profile opens on row tap.',
  },
  {
    id: 'search-stocks',
    phase: 'discovery',
    name: 'Search stocks results',
    screen: 'SearchStocksScreen',
    status: 'built',
    preconditions: 'Query matches tickers.',
    userAction: 'Select a stock row.',
    expectedResult: 'Navigate to Markets stock detail with community feed tabs.',
  },
  {
    id: 'follow-user',
    phase: 'discovery',
    name: 'Follow / unfollow user',
    screen: 'FollowUserScreen',
    status: 'built',
    preconditions: 'Viewing another user profile or search result.',
    userAction: 'Tap Follow; later tap Following to unfollow.',
    expectedResult: 'Button toggles; Following feed and activity include/exclude user.',
  },

  // Markets & portfolio tab
  {
    id: 'portfolio-holdings',
    phase: 'markets',
    name: 'Portfolio tab — holdings',
    screen: 'PortfolioHoldingsScreen',
    status: 'built',
    preconditions: 'Portfolio tab; Holdings selected.',
    userAction: 'View allocation; change period; tap holding.',
    expectedResult: 'Summary metrics, distribution bar, sub-tabs Summary/News/Trades/Posts; holding → stock detail.',
  },
  {
    id: 'portfolio-watchlist',
    phase: 'markets',
    name: 'Create watchlist',
    screen: 'WatchlistCreateScreen',
    status: 'built',
    preconditions: 'Portfolio tab; watchlists sub-tab.',
    userAction: 'Tap New list; name list; add symbols.',
    expectedResult: 'Watchlist saved; appears in selector; symbols searchable.',
  },
  {
    id: 'markets-movers',
    phase: 'markets',
    name: 'Markets movers',
    screen: 'MarketsMoversScreen',
    status: 'built',
    preconditions: 'Markets tab.',
    userAction: 'Switch Movers/Gainers/Losers; search; tap row.',
    expectedResult: 'Filtered stock list with sparklines; row opens stock detail.',
  },
  {
    id: 'stock-detail',
    phase: 'markets',
    name: 'Stock detail',
    screen: 'StockDetailScreen',
    status: 'built',
    preconditions: 'Ticker selected from Markets, Portfolio, or Search.',
    userAction: 'Read price summary; switch Summary/News/Trades/Posts tabs.',
    expectedResult: 'Community activity for symbol; posts and trades from holders; back via shell on mobile.',
  },

  // Profile
  {
    id: 'profile-own',
    phase: 'profile',
    name: 'Own profile — edit',
    screen: 'ProfileOwnScreen',
    status: 'built',
    preconditions: 'Profile tab; private view.',
    userAction: 'Edit About; switch tabs; toggle Public preview.',
    expectedResult: 'Inline edits to name/bio; tabs Posts/About/Portfolios/Trades; preview shows public rendering.',
  },
  {
    id: 'profile-public',
    phase: 'profile',
    name: 'Public profile (other user)',
    screen: 'ProfilePublicScreen',
    status: 'built',
    preconditions: 'Opened another user from feed or search.',
    userAction: 'View posts, portfolios, trades; Follow.',
    expectedResult: 'Read-only hero + tabs; holdings and XIRR visible; Follow CTA in hero.',
  },
  {
    id: 'portfolio-add',
    phase: 'profile',
    name: 'Add portfolio',
    screen: 'PortfolioAddScreen',
    status: 'built',
    preconditions: 'Own profile → Portfolios tab.',
    userAction: 'Tap Add portfolio; enter name, objective, thesis.',
    expectedResult: 'New portfolio in list; opens detail for holdings entry.',
  },
  {
    id: 'portfolio-edit',
    phase: 'profile',
    name: 'Edit portfolio holdings',
    screen: 'PortfolioEditScreen',
    status: 'built',
    preconditions: 'Portfolio detail open (own profile).',
    userAction: 'Add/update/remove holdings.',
    expectedResult: 'Holdings table updates; trade auto-logged in Trades tab and activity feed.',
  },

  // Activity
  {
    id: 'activity-unread',
    phase: 'activity',
    name: 'Activity with unread badge',
    screen: 'ActivityUnreadScreen',
    status: 'built',
    preconditions: 'New activity since last visit.',
    userAction: 'Tap Activity in nav.',
    expectedResult: 'Badge clears; sections From people you follow + From your holdings; items deep-link.',
  },
  {
    id: 'activity-post-tap',
    phase: 'activity',
    name: 'Activity → post',
    screen: 'ActivityPostScreen',
    status: 'built',
    preconditions: 'Activity item is a followed user post.',
    userAction: 'Tap activity row.',
    expectedResult: 'Opens post detail; item marked read.',
  },

  // Settings
  {
    id: 'settings',
    phase: 'settings',
    name: 'Settings',
    screen: 'SettingsScreen',
    status: 'built',
    preconditions: 'Logged in.',
    userAction: 'Open settings from profile menu.',
    expectedResult: 'Notification prefs, connected accounts, disclosure info, legal links.',
  },
  {
    id: 'logout',
    phase: 'settings',
    name: 'Log out',
    screen: 'LogoutScreen',
    status: 'built',
    preconditions: 'Settings open.',
    userAction: 'Tap Log out; confirm.',
    expectedResult: 'Session cleared; return to marketing home.',
  },
];

export function scenariosByPhase(phaseId) {
  return SOCIAL_USER_SCENARIOS.filter((s) => s.phase === phaseId);
}
